### ISSUE TITLE
setup.py data copy fails

### ISSUE THREAD

**Issue by luigima** [MikePia/structjour#2]
> error: can't copy 'data\ActivityStatement.20190313_PL.html': doesn't exist or not a regular file

Errors show up when I run setup.py install as files within the data directory are excluded in .gitignore. Seems to be personal files? You might want to remove them from setup.py

**Comment by MikePia** [comment]
Got it. They are gone. Please let me know any other problems

**Comment by MikePia** [comment]
Are you Luke from BBT?

**Comment by luigima** [comment]
I am! :P

After installation the app crashes with `ModuleNotFoundError: No module named 'PyQt5.sip'`. Do you happen to know what is wrong? Unfortunately I have no experiences with pyqt5.

**Comment by MikePia** [comment]
You should be able to fix that with
pip install pyqt5-sip

I think it should have been installed as a dependency of pyqt5. But if this fixes it, I’ll add it to the dependency list in setup.py

**Comment by luigima** [comment]
Using a fresh python install I still cannot fix it unfortunately.  Maybe you can do an install from scratch on a Windows VM yourself and see if you can reproduce the error?

**Comment by MikePia** [comment]
I have updated the setup.py dependencies to include pyqt5-sip
I'm not sure what the error is.
What do you do to get the error message? Is it during the install or when you run structjour.exe?
I get the following if I uninstall pipqt5-sip and run structjour.exe. 

pkg_resources.DistributionNotFound: The 'PyQt5_sip<13,>=4.19.19' distribution was not found and is required by PyQt5



Did  pyqt5-sip get successfully installed?
List your installed python packages with
python -m pip list
If its not installed, it may get a helpful error message when you try to install it:
python -m pip install pyqt5-sip

**Comment by MikePia** [comment]
Could you please print out the entire error. Does it occur when you run the structjour.exe command?

**Comment by luigima** [comment]
```
python.exe --version
Python 3.7.4
```

```
pip list
Package         Version
--------------- -------
beautifulsoup4  4.8.0
cycler          0.10.0
et-xmlfile      1.0.1
jdcal           1.4.1
kiwisolver      1.1.0
matplotlib      3.1.1
mpl-finance     0.10.0
numpy           1.17.2
openpyxl        2.5.14
pandas          0.25.1
pip             19.0.3
pyparsing       2.4.2
pyqt5           5.13.1
pyqt5-sip       4.19.19
pyqtwebengine   5.13.1
python-dateutil 2.8.0
pytz            2019.2
scipy           1.3.1
seaborn         0.9.0
setuptools      40.8.0
six             1.12.0
soupsieve       1.9.3
structjour      0.9.9a0
```

```
...\Python37\Scripts>structjour.exe
Traceback (most recent call last):
  File "...\Python37\Scripts\structjour-script.py", line 11, in <module>
    load_entry_point('structjour==0.9.9a0', 'console_scripts', 'structjour')()
  File "...\Python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "...\Python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "...\Python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "...\Python37\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "...\Python37\lib\site-packages\structjour-0.9.9a0-py3.7.egg\structjour\view\runtrade.py", line 28, in <module>
    from PyQt5.QtCore import QDate, QDateTime
ModuleNotFoundError: No module named 'PyQt5.sip'
```

**Comment by MikePia** [comment]
From  a Stack question:

uninstall pyqt5 and pyqt5-tools packages and then reinstall them.

Of course if it works, it gives me no clue how to fix my setup.py for a clean install

**Comment by luigima** [comment]
Yeah I saw this as well but it doesn't fix it as expected

**Comment by MikePia** [comment]
The good news, I can reliably reproduce and fix the error by uninstalling all dependencies and then installing with
python setup.py sdist install

Then I can fix them with:
pip uninstall -y  pyqtwebengine pyqt5 pyqt5-sip
pip install  structjour

**Comment by MikePia** [comment]
I am going to close the original issue and open a new one that address the PyQt5 install stuff.  Please reply to that thread and your help is appreciated

**Comment by MikePia** [comment]
Should work now
